"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { CreditCard, Plus, ReceiptText, WalletCards } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { useTranslation } from "react-i18next";
import { z } from "zod";
import { useToast } from "@/lib/toast-provider";
import { FieldShell,inputClassName,selectClassName } from "@/modules/forms/form-controls";
import type { Payment,PaymentStatus } from "@/services/payment.service";
import { EmptyState } from "@/shared/components/common/empty-state";
import { LoadingSkeleton } from "@/shared/components/common/loading-skeleton";
import { Badge } from "@/shared/components/ui/badge";
import { Button } from "@/shared/components/ui/button";
import { Dialog } from "@/shared/components/ui/dialog";
import { toErrorMessage } from "@/shared/utils/error.util";
import { useCreatePayment,usePayments,useRefundPayment } from "../hooks/use-payment";
import { createPaymentSchema,refundSchema } from "../schemas";

const statuses:PaymentStatus[]=["PENDING","COMPLETED","FAILED","REFUNDED","PARTIALLY_REFUNDED"];
const money=(value:number|undefined,lang:string)=>new Intl.NumberFormat(lang==="vi"?"vi-VN":"en-US",{style:"currency",currency:"VND",maximumFractionDigits:0}).format(value??0);
export function PaymentsPage({scope}:{scope:"customer"|"pt"}){
 const {t,i18n}=useTranslation();const [status,setStatus]=useState<PaymentStatus|"">("");const [creating,setCreating]=useState(false);const [refunding,setRefunding]=useState<Payment|null>(null);const query=usePayments(scope,status||undefined);const items=query.data?.content??[];
 const total=items.reduce((sum,p)=>sum+(scope==="pt"?(p.ptEarning??0):(p.amount??0)),0);
 return <div><section className="mb-6 flex flex-col gap-5 rounded-3xl border border-zinc-200 bg-white/80 p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-950/80 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-3 h-1 w-10 rounded-full bg-orange-500"/><h1 className="text-3xl font-black">{t(`payment.${scope}Title`)}</h1><p className="mt-2 text-sm text-zinc-500">{t(`payment.${scope}Description`)}</p></div>{scope==="customer"&&<Button onClick={()=>setCreating(true)}><Plus className="size-4"/>{t("payment.create")}</Button>}</section>
 {!!items.length&&<div className="mb-5 flex items-center gap-4 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950"><WalletCards className="size-7 text-lime-600"/><div><p className="text-xs font-black uppercase text-zinc-400">{t(scope==="pt"?"payment.totalEarning":"payment.totalAmount")}</p><p className="text-2xl font-black">{money(total,i18n.language)}</p></div></div>}
 <select className={selectClassName} value={status} onChange={e=>setStatus(e.target.value as PaymentStatus|"")}><option value="">{t("payment.allStatuses")}</option>{statuses.map(s=><option key={s} value={s}>{t(`payment.statuses.${s}`)}</option>)}</select>
 <div className="mt-5">{query.isLoading?<LoadingSkeleton/>:query.isError?<EmptyState title={t("payment.loadError")} description={toErrorMessage(query.error)}/>:!items.length?<EmptyState title={t("payment.empty")} description={t("payment.emptyDescription")}/>:<div className="grid gap-4 lg:grid-cols-2">{items.map(p=><article key={p.id} className="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-950"><div className="flex justify-between"><p className="text-xs font-black uppercase text-zinc-400">#{p.id} · Booking #{p.bookingId}</p><Badge>{p.status?t(`payment.statuses.${p.status}`):"—"}</Badge></div><h2 className="mt-2 text-xl font-black">{money(scope==="pt"?p.ptEarning:p.amount,i18n.language)}</h2><div className="mt-3 grid gap-1 text-sm text-zinc-500"><span>{t("payment.customer")}: {p.customerName}</span><span>{t("payment.trainer")}: {p.ptName}</span><span>{t("payment.method")}: {p.paymentMethod?t(`payment.methods.${p.paymentMethod}`):"—"}</span></div>{scope==="customer"&&p.status==="COMPLETED"&&<Button className="mt-4 bg-red-600" onClick={()=>setRefunding(p)}>{t("payment.refund")}</Button>}</article>)}</div>}</div>
 <CreatePaymentDialog open={creating} onClose={()=>setCreating(false)}/>{refunding&&<RefundDialog payment={refunding} onClose={()=>setRefunding(null)}/>}</div>;
}
function CreatePaymentDialog({open,onClose}:{open:boolean;onClose:()=>void}){const{t}=useTranslation();const{toast}=useToast();const mutation=useCreatePayment();const form=useForm<z.infer<typeof createPaymentSchema>>({resolver:zodResolver(createPaymentSchema),defaultValues:{bookingId:0,paymentMethod:"VNPAY"}});return <Dialog open={open} title={t("payment.create")} onClose={onClose}><form className="space-y-4" onSubmit={form.handleSubmit(async v=>{try{await mutation.mutateAsync({bookingId:v.bookingId,payload:{paymentMethod:v.paymentMethod}});toast({type:"success",title:t("payment.created")});onClose();}catch(e){toast({type:"error",title:t("common.requestFailed"),description:toErrorMessage(e)});}})}><FieldShell label={t("payment.bookingId")} error={form.formState.errors.bookingId}><input type="number" className={inputClassName} {...form.register("bookingId",{valueAsNumber:true})}/></FieldShell><FieldShell label={t("payment.method")}><select className={selectClassName} {...form.register("paymentMethod")}>{["VNPAY","MOMO","BANK_TRANSFER","CASH"].map(m=><option key={m} value={m}>{t(`payment.methods.${m}`)}</option>)}</select></FieldShell><Button disabled={mutation.isPending}><CreditCard className="size-4"/>{t("payment.pay")}</Button></form></Dialog>}
function RefundDialog({payment,onClose}:{payment:Payment;onClose:()=>void}){const{t}=useTranslation();const{toast}=useToast();const mutation=useRefundPayment();const form=useForm<z.infer<typeof refundSchema>>({resolver:zodResolver(refundSchema),defaultValues:{amount:payment.amount??0,reason:""}});return <Dialog open title={t("payment.refund")} onClose={onClose}><form className="space-y-4" onSubmit={form.handleSubmit(async v=>{try{await mutation.mutateAsync({id:payment.id!,payload:v});toast({type:"success",title:t("payment.refunded")});onClose();}catch(e){toast({type:"error",title:t("common.requestFailed"),description:toErrorMessage(e)});}})}><FieldShell label={t("payment.refundAmount")}><input type="number" className={inputClassName} {...form.register("amount",{valueAsNumber:true})}/></FieldShell><FieldShell label={t("payment.refundReason")}><textarea className={inputClassName} {...form.register("reason")}/></FieldShell><Button className="bg-red-600" disabled={mutation.isPending}><ReceiptText className="size-4"/>{t("payment.refund")}</Button></form></Dialog>}
